/* AI-generated town "vibe" reads (lifestyle & character, not demographics).
   s = cool score 1-5, v = blurb, t = tags. Seeded for CA/OR now; the scraper
   fills in the rest nationwide when an AI key is set. Estimates — do your own
   homework on any specific neighborhood. */
window.VIBES = {
  "Anaheim, CA": {s:3, v:"Big Orange County city — Disneyland, sports, busy suburban energy.", t:["theme parks","suburban"]},
  "Angels Camp, CA": {s:3, v:"Historic Gold Country town in the Sierra foothills, quaint Main Street.", t:["historic","foothills"]},
  "Antioch, CA": {s:2, v:"East Bay/Delta commuter city — the affordable edge of the Bay Area.", t:["bay-area commute","affordable"]},
  "Arnold, CA": {s:3, v:"Sierra pine town near Bear Valley skiing — cabins and big trees.", t:["mountains","ski","cabins"]},
  "Banning, CA": {s:2, v:"Pass town between the Inland Empire and Palm Springs, budget desert gateway.", t:["desert gateway","affordable"]},
  "Blythe, CA": {s:1, v:"Remote Colorado River farm town — hot, agricultural, river recreation.", t:["river","remote"]},
  "Borrego Springs, CA": {s:3, v:"Desert oasis inside Anza-Borrego — dark skies, wildflowers, quiet and artsy.", t:["desert","dark-sky","artsy"]},
  "Campo, CA": {s:1, v:"Rural backcountry near the border — ranch land, very remote.", t:["rural","remote"]},
  "Carmichael, CA": {s:3, v:"Leafy Sacramento suburb along the American River — established and family.", t:["sacramento suburb","river"]},
  "Clearlake Oaks, CA": {s:2, v:"Budget lakefront on Clear Lake — fishing, boating, rural NorCal.", t:["lake","budget"]},
  "Cloverdale, CA": {s:3, v:"North Sonoma wine-country gateway — small-town and slowly on the rise.", t:["wine country","up-and-coming"]},
  "Coarsegold, CA": {s:2, v:"Sierra foothills on the road to Yosemite — oak country, rural.", t:["foothills","Yosemite gateway"]},
  "Central Point, OR": {s:3, v:"Rogue Valley town by Medford — Rogue Creamery, easy family living.", t:["Rogue Valley","family"]},
  "Coos Bay, OR": {s:3, v:"Southern Oregon coast port — working waterfront, rugged coast, affordable.", t:["coast","working town"]},
  "Eugene, OR": {s:4, v:"University of Oregon college town — green, artsy, outdoorsy, track-crazy.", t:["college","outdoorsy","artsy"]},
  "Fairfield, CA": {s:2, v:"Mid-way commuter city between SF and Sacramento — practical, suburban.", t:["commuter","suburban"]},
  "Florence, OR": {s:3, v:"Oregon coast dunes town — old-town charm, retirees, giant sand dunes.", t:["coast","dunes"]},
  "Forestville, CA": {s:4, v:"Russian River wine hamlet among the redwoods — laid-back Sonoma.", t:["wine country","redwoods","river"]},
  "Fort Jones, CA": {s:2, v:"Tiny Scott Valley ranch town under the Marble Mountains — remote.", t:["rural","mountains"]},
  "Grants Pass, OR": {s:3, v:"Rogue River rafting town — outdoorsy, growing, retiree-friendly.", t:["river","outdoorsy"]},
  "Groveland, CA": {s:3, v:"Historic Yosemite gateway on Highway 120 — quaint and scenic.", t:["Yosemite gateway","historic"]},
  "Hemet, CA": {s:2, v:"Inland valley — affordable, hot, lots of quiet retirement neighborhoods.", t:["affordable","valley"]},
  "La Pine, OR": {s:3, v:"High-desert town near Bend — the budget-friendly outdoorsy alternative.", t:["Bend-adjacent","outdoorsy","affordable"]},
  "Lakeview, OR": {s:1, v:"Remote high-desert ranch town — hot springs, very off-the-beaten-path.", t:["remote","high desert"]},
  "Langlois, OR": {s:2, v:"Tiny south-coast Oregon hamlet — rural and coastal.", t:["coast","tiny"]},
  "Littlerock, CA": {s:1, v:"High-desert Antelope Valley — fruit orchards, affordable, remote-ish.", t:["high desert","affordable"]},
  "Lone Pine, CA": {s:4, v:"Eastern Sierra film-history town under Mt. Whitney — stunning and outdoorsy.", t:["Eastern Sierra","scenic","outdoorsy"]},
  "Madera, CA": {s:2, v:"Central Valley ag city — affordable, farm and wine country.", t:["central valley","affordable"]},
  "Mi Wuk Village, CA": {s:2, v:"Sierra pine cabin community near Twain Harte — quiet mountains.", t:["mountains","cabins"]},
  "Modesto, CA": {s:2, v:"Central Valley hub — birthplace of American Graffiti, ag, affordable.", t:["central valley","affordable"]},
  "Montague, CA": {s:1, v:"Tiny Siskiyou high-valley town near Yreka — remote, rural.", t:["remote","rural"]},
  "Myrtle Point, OR": {s:2, v:"Small Coquille Valley timber town in rural southwest Oregon.", t:["rural","timber"]},
  "Napa, CA": {s:5, v:"Wine Country capital — upscale, foodie, walkable riverfront, tourist magnet.", t:["wine country","upscale","foodie"]},
  "Newport Beach, CA": {s:5, v:"Ritzy Orange County beach city — harbor, surf, sailing, big money.", t:["beach","upscale","coastal"]},
  "Nice, CA": {s:2, v:"Clear Lake north-shore town — budget lakefront, rural.", t:["lake","budget"]},
  "Oregon City, OR": {s:4, v:"Historic end of the Oregon Trail — waterfalls, Portland metro, up-and-coming.", t:["Portland metro","historic","up-and-coming"]},
  "Palm Desert, CA": {s:4, v:"Coachella Valley resort city — golf, El Paseo shopping, upscale desert.", t:["desert resort","golf","upscale"]},
  "Palmdale, CA": {s:2, v:"Antelope Valley aerospace/commuter city — affordable high desert.", t:["high desert","affordable"]},
  "Pine Grove, CA": {s:2, v:"Amador Gold Country foothills — pines, quiet, small.", t:["foothills","quiet"]},
  "Placerville, CA": {s:4, v:"Historic Gold Country Hangtown — charming Main Street, wine, on the rise.", t:["historic","wine","charming"]},
  "Pleasant Hill, CA": {s:3, v:"Comfortable East Bay suburb — family, good schools, convenient.", t:["bay-area suburb","family"]},
  "Portland, OR": {s:5, v:"Iconic PNW city — food, coffee, beer, arts, quirky and very walkable.", t:["city","foodie","walkable","arts"]},
  "Red Bluff, CA": {s:2, v:"North-valley rodeo and ranch town on the Sacramento River — affordable, hot.", t:["rural","river","affordable"]},
  "Redding, CA": {s:3, v:"North State hub — Sundial Bridge, lakes and trails, gateway to Shasta.", t:["outdoorsy","gateway"]},
  "Running Springs, CA": {s:3, v:"San Bernardino mountains between Big Bear and Lake Arrowhead — pines.", t:["mountains","cabins"]},
  "Sacramento, CA": {s:4, v:"State capital — farm-to-fork food scene, midtown revival, rivers, getting hip.", t:["city","foodie","up-and-coming"]},
  "San Jacinto, CA": {s:2, v:"Inland valley next to Hemet — affordable and steadily growing.", t:["affordable","valley"]},
  "Shingletown, CA": {s:2, v:"Forest community on the road to Lassen — remote pines.", t:["forest","remote"]},
  "Signal Hill, CA": {s:3, v:"Hilltop enclave ringed by Long Beach — big city views, walk to LB.", t:["LA metro","views","coastal-adjacent"]},
  "Sisters, OR": {s:5, v:"Adorable Cascade resort town near Bend — Western-themed, artsy, outdoorsy.", t:["mountains","charming","outdoorsy"]},
  "Sonora, CA": {s:4, v:"Gold Country queen city — historic charming Main Street, foothills, artsy.", t:["historic","foothills","charming"]},
  "Springfield, OR": {s:3, v:"Eugene's blue-collar twin — affordable and revitalizing.", t:["affordable","up-and-coming"]},
  "Sun City, CA": {s:2, v:"Menifee-area 55+ retirement community — quiet and affordable.", t:["retirement","affordable"]},
  "Three Rivers, CA": {s:4, v:"Sequoia gateway — foothills, an artsy river town, gorgeous.", t:["park gateway","artsy","scenic"]},
  "Tillamook, OR": {s:3, v:"Oregon coast dairy town (yes, the cheese) — working coast, family.", t:["coast","family"]},
  "Twentynine Palms, CA": {s:3, v:"Joshua Tree gateway — desert-boho, artsy, Marine-base town.", t:["desert","park gateway","artsy"]},
  "Yachats, OR": {s:5, v:"Gem of a tiny Oregon coast village — dramatic coast, artsy, beloved.", t:["coast","charming","artsy"]},
  "Yreka, CA": {s:2, v:"Historic far-north gold town near Mt. Shasta — Main Street, remote.", t:["historic","remote"]}
};
